language: java
jdk:
  - openjdk17

before_install:
  - chmod +x gradlew

script:
  - ./gradlew build

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'

after_success:
  - ./gradlew test

