language: java
jdk:
  - openjdk17

before_install:
  - chmod +x gradlew

script:
  - ./gradlew build
  - ./gradlew build jacocoTestReport

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'

after_success:
  - ./gradlew test
  - ./gradlew jacocoTestReport coveralls
  - bash <(curl -s https://codecov.io/bash)